/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package me.hron.koponyeg;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f070000;
        public static final int btCloud=0x7f070002;
        public static final int preferences=0x7f070003;
        public static final int quit=0x7f070004;
        public static final int wvMain=0x7f070001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int widget=0x7f030001;
    }
    public static final class menu {
        public static final int mainmenu=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f050003;
        public static final int description=0x7f050004;
        public static final int menu_quit=0x7f050000;
        public static final int menu_settings=0x7f050001;
        public static final int settings=0x7f050002;
        public static final int town=0x7f050005;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
        public static final int widget=0x7f040001;
    }
}
